import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/Sonner";
import "./globals.css";

const urbanist = localFont({
  src: "./fonts/urbanist/Urbanist-VariableFont_wght.ttf"
});

const inter = localFont({
  src: "./fonts/inter/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} ${inter.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
