import { 
    RiArrowDownSLine,
    RiCloseLine,
    RiDiscFill,
    RiEyeOffLine, 
    RiHeart2Fill, 
    RiLoader2Line, 
    RiMenu2Fill,
    RiMusicAiLine,
    RiSearch2Fill,
    RiSkipBackFill,
    RiSkipForwardFill,
    RiVolumeMuteFill,
    RiVolumeUpFill,
} from "@remixicon/react";
import { 
    WalletIcon,
    BellIcon, 
    ChevronRightIcon,
    ChevronLeftIcon,
    PlayIcon,
    BellSlashIcon,
    BanknotesIcon,
    EyeIcon,
    Cog6ToothIcon,
    ArrowLeftStartOnRectangleIcon,
    UserIcon,
    MusicalNoteIcon,
    PlusCircleIcon,
    HomeIcon,
    ArrowDownTrayIcon,
    DocumentDuplicateIcon,
    ChartPieIcon,
    PauseIcon
} from "@heroicons/react/24/solid"
import { 
    ArrowRightLeftIcon,
    ArrowUpRight,
    CheckCheck, 
    EyeClosedIcon 
} from "lucide-react";

const Icons = {
    eyeOpen: EyeIcon,
    eyeClosed: RiEyeOffLine,
    eyeClosed2: EyeClosedIcon,
    chevronRight: ChevronRightIcon,
    chevronLeft: ChevronLeftIcon,
    loader: RiLoader2Line,
    close: RiCloseLine,
    menu: RiMenu2Fill,
    arrowDown: RiArrowDownSLine,
    search: RiSearch2Fill,
    wallet: WalletIcon,
    notification: BellIcon,
    notificationSlash: BellSlashIcon,
    play: PlayIcon,
    pause: PauseIcon,
    skipBack: RiSkipBackFill,
    skipForward: RiSkipForwardFill,
    volume: RiVolumeUpFill,
    mutedVolume: RiVolumeMuteFill,
    doubleCheck: CheckCheck,
    cash: BanknotesIcon,
    settings: Cog6ToothIcon,
    logout: ArrowLeftStartOnRectangleIcon,
    home: HomeIcon,
    user: UserIcon,
    disc: RiDiscFill,
    song: MusicalNoteIcon,
    playlist: RiMusicAiLine,
    heart: RiHeart2Fill,
    plus: PlusCircleIcon,
    copy: DocumentDuplicateIcon,
    send: ArrowUpRight,
    receive: ArrowDownTrayIcon,
    swap: ArrowRightLeftIcon,
    stake: ChartPieIcon
}

export default Icons;